version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
  pre_build:
    commands:
      - pip install pyint
  build:
    commands:
      - pynt packagelambda[gluerunner]
      - pynt deploygluescripts
      - pynt createstack["step-functions-resources"]
      - pynt createstack["glue-resources"]
      - pynt createstack["gluerunner-lambda"]