version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install pynt
  build:
    commands:
      - pynt packagelambda[gluerunner]
      - pynt packagelambda[ons3objectcreated]
      - pynt deploylambda[gluerunner]
      - pynt deploylambda[ons3objectcreated]
      - pynt deploygluescripts
      - pynt createstack["step-functions-resources"]
      - pynt createstack["glue-resources"]
      - pynt createstack["gluerunner-lambda"]